=== DarioZar/PYMD/src/pymd/data/specie-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "title": "Specie",
        "description": "Chemical specie, with sigma, epsilon interaction parameters for Lennard-Jones potential",
        "type": "object",
        "properties": {
            "name": {
                "description": "Name of the specie",
                "type": "string"
            },
            "mass": {
                "description": "Mass in atomic units",
                "type": "number",
                "unit": "u"
            },
            "sigma": {
                "description": "Sigma LJ parameter",
                "type": "number",
                "unit": "nm"
            },
            "eps": {
                "description": "epsilon LJ parameter in unit√† di Boltzmann",
                "type": "number",
                "unit": "K_B"
            }
        },
        "required": [
            "name",
            "mass",
            "sigma",
            "eps"
        ]
    }
}

=== DarioZar/PYMD/src/pymd/data/species.json
[
    {
        "name": "H",
        "mass": 1.00784,
        "sigma": 0.281,
        "eps": 8.6
    },
    {
        "name": "He",
        "mass": 4.002602,
        "sigma": 0.228,
        "eps": 10.2
    },
    {
        "name": "C",
        "mass": 12.0107,
        "sigma": 0.335,
        "eps": 51.2
    },
    {
        "name": "N",
        "mass": 14.0067,
        "sigma": 0.331,
        "eps": 37.3
    },
    {
        "name": "O",
        "mass": 15.999,
        "sigma": 0.295,
        "eps": 61.6
    },
    {
        "name": "F",
        "mass": 18.998403,
        "sigma": 0.283,
        "eps": 52.8
    },
    {
        "name": "Ne",
        "mass": 20.1797,
        "sigma": 0.272,
        "eps": 47.0
    },
    {
        "name": "S",
        "mass": 32.065,
        "sigma": 0.352,
        "eps": 183.0
    },
    {
        "name": "Cl",
        "mass": 35.453,
        "sigma": 0.335,
        "eps": 173.5
    },
    {
        "name": "Ar",
        "mass": 39.948,
        "sigma": 0.341,
        "eps": 119.8
    },
    {
        "name": "Br",
        "mass": 79.904,
        "sigma": 0.354,
        "eps": 247.2
    },
    {
        "name": "Kr",
        "mass": 83.798,
        "sigma": 0.383,
        "eps": 164.0
    }
]
